const same = (s) => ({ me: s, en: s, it: s, ru: s });

export const menu = [
  {
    id: 'kafa',
    name: { me: 'Topli napici', en: 'Hot drinks', it: 'Bevande calde', ru: 'Горячие напитки' },
    items: [
      { name: same('Espresso'), price: '1.40' },
      { name: { me: 'Espresso sa mlijekom', en: 'Espresso with milk', it: 'Espresso con latte', ru: 'Эспрессо с молоком' }, price: '1.50' },
      { name: same('Deutch caffe'), price: '1.70' },
      { name: same('Cappuccino'), price: '1.90' },
      { name: same('Latte Macchiato'), price: '2.00' },
      { name: { me: 'Kuvana kafa', en: 'Turkish coffee', it: 'Caffè alla turca', ru: 'Кофе по-турецки' }, price: '1.60' },
      { name: same('Nesscaffe'), price: '2.00' },
      { name: { me: 'Topla čokolada', en: 'Hot chocolate', it: 'Cioccolata calda', ru: 'Горячий шоколад' }, price: '3.00' },
      { name: { me: 'Čaj', en: 'Tea', it: 'Tè', ru: 'Чай' }, price: '2.00' },
      { name: same('Čaj Alt Haus'), price: '2.40' },
      { name: same('Ice Coffee'), price: '2.00' },
      { name: same('Affogato'), price: '2.50' },
    ],
  },
  {
    id: 'sokovi',
    name: { me: 'Sokovi', en: 'Soft drinks & juices', it: 'Bibite e succhi', ru: 'Соки и напитки' },
    items: [
      { name: same('Coca Cola'), price: '2.80' },
      { name: same('Coca Cola Zero'), price: '2.80' },
      { name: same('Fanta'), price: '2.80' },
      { name: same('Sprite'), price: '2.80' },
      { name: same('Schweppes Bitter Lemon'), price: '2.80' },
      { name: same('Schweppes Tonic Water'), price: '2.80' },
      { name: same('Cockta'), price: '2.40' },
      { name: same('Orangina'), price: '3.20' },
      { name: same('Cedevita'), price: '2.00' },
      { name: { me: 'Negazirani sok', en: 'Still juice', it: 'Succo non gassato', ru: 'Негазированный сок' }, price: '2.80' },
      { name: { me: 'Grejp', en: 'Grapefruit juice', it: 'Succo di pompelmo', ru: 'Грейпфрутовый сок' }, price: '3.00' },
      { name: { me: 'Limunada', en: 'Lemonade', it: 'Limonata', ru: 'Лимонад' }, price: '2.50' },
      { name: { me: 'Cijeđena pomorandža', en: 'Fresh orange juice', it: "Spremuta d'arancia", ru: 'Свежевыжатый апельсиновый сок' }, price: '3.30' },
      { name: { me: 'Jabuka', en: 'Apple juice', it: 'Succo di mela', ru: 'Яблочный сок' }, price: '3.00' },
      { name: { me: 'Mix', en: 'Mixed juice', it: 'Succo misto', ru: 'Микс сок' }, price: '3.50' },
      { name: { me: 'Američka limunada', en: 'American lemonade', it: 'Limonata americana', ru: 'Американский лимонад' }, price: '2.80' },
      { name: { me: 'Ledeni čaj', en: 'Iced tea', it: 'Tè freddo', ru: 'Холодный чай' }, price: '2.00' },
      { name: same('San Pellegrino'), price: '2.80' },
    ],
  },
  {
    id: 'vode',
    name: { me: 'Vode i energetska pića', en: 'Water & energy drinks', it: 'Acqua e energetici', ru: 'Вода и энергетики' },
    items: [
      { name: { me: 'Voda', en: 'Still water', it: 'Acqua naturale', ru: 'Вода без газа' }, size: '0.25l', price: '1.60' },
      { name: { me: 'Kisjela voda', en: 'Sparkling water', it: 'Acqua frizzante', ru: 'Газированная вода' }, size: '0.25l', price: '2.20' },
      { name: same('Red Bull'), price: '3.50' },
    ],
  },
  {
    id: 'sladoled',
    name: { me: 'Sladoled', en: 'Ice cream', it: 'Gelato', ru: 'Мороженое' },
    items: [
      { name: { me: 'Sladoled — kugla', en: 'Ice cream — scoop', it: 'Gelato — pallina', ru: 'Мороженое — шарик' }, price: '1.50' },
      { name: { me: 'Sladoled — akcija', en: 'Ice cream — special', it: 'Gelato — offerta', ru: 'Мороженое — акция' }, price: '0.80' },
    ],
  },
  {
    id: 'piva',
    name: { me: 'Piva', en: 'Beer', it: 'Birra', ru: 'Пиво' },
    groups: [
      {
        label: { me: 'Flaširana', en: 'Bottled', it: 'In bottiglia', ru: 'В бутылках' },
        items: [
          { name: same('Heineken'), size: '0.25l', price: '3.50' },
          { name: same('Heineken Silver'), size: '0.25l', price: '2.50' },
          { name: same('Birra Moretti'), size: '0.33l', price: '2.50' },
          { name: same('Zaječarko'), size: '0.33l', price: '2.80' },
          { name: { me: 'Zaječarko tamno', en: 'Zaječarko Dark', it: 'Zaječarko scura', ru: 'Zaječarko тёмное' }, size: '0.33l', price: '2.20' },
        ],
      },
      {
        label: { me: 'Točeno', en: 'Draft', it: 'Alla spina', ru: 'Разливное' },
        items: [
          { name: { me: 'Heineken točeno', en: 'Heineken (draft)', it: 'Heineken (alla spina)', ru: 'Heineken (разливное)' }, size: '0.25l', price: '3.00' },
          { name: { me: 'Zaječarsko točeno', en: 'Zaječarsko (draft)', it: 'Zaječarsko (alla spina)', ru: 'Zaječarsko (разливное)' }, size: '0.30l', price: '2.00' },
        ],
      },
    ],
  },
  {
    id: 'vina',
    name: { me: 'Vina', en: 'Wine', it: 'Vino', ru: 'Вино' },
    items: [
      { name: same('Pro Corde'), size: '0.187l', price: '4.00' },
      { name: same('Vranac Vrhunski'), size: '0.187l', price: '3.50' },
      { name: same('Chardonnay'), size: '0.187l', price: '3.50' },
      { name: same('Graševina'), size: '0.187l', price: '4.00' },
      { name: same('Rose'), size: '0.187l', price: '3.50' },
      { name: { me: 'Kuvano vino', en: 'Mulled wine', it: 'Vin brûlé', ru: 'Глинтвейн' }, price: '2.50' },
    ],
  },
  {
    id: 'rakija',
    name: { me: 'Rakija', en: 'Rakija (brandy)', it: 'Rakija (acquavite)', ru: 'Ракия' },
    items: [
      { name: same('Loza Institut'), size: '0.03l', price: '2.50' },
      { name: same('Kruna'), size: '0.03l', price: '2.50' },
      { name: same('Prvijenac'), size: '0.03l', price: '2.20' },
      { name: same('Loza 13 Jul'), size: '0.03l', price: '2.00' },
      { name: same('Meduška'), size: '0.03l', price: '2.00' },
      { name: { me: 'Viljamovka', en: 'Viljamovka (pear)', it: 'Viljamovka (pera)', ru: 'Viljamovka (груша)' }, size: '0.03l', price: '2.20' },
      { name: { me: 'Dunja', en: 'Dunja (quince)', it: 'Dunja (mela cotogna)', ru: 'Dunja (айва)' }, size: '0.03l', price: '3.20' },
      { name: { me: 'Šljiva', en: 'Šljiva (plum)', it: 'Šljiva (prugna)', ru: 'Šljiva (слива)' }, size: '0.03l', price: '3.20' },
      { name: { me: 'Kajsija', en: 'Kajsija (apricot)', it: 'Kajsija (albicocca)', ru: 'Kajsija (абрикос)' }, size: '0.03l', price: '2.80' },
      { name: same('Jelički Dukat'), size: '0.03l', price: '4.50' },
    ],
  },
  {
    id: 'likeri',
    name: { me: 'Likeri', en: 'Liqueurs', it: 'Liquori', ru: 'Ликёры' },
    items: [
      { name: same('Jegermeister'), size: '0.03l', price: '2.20' },
      { name: { me: 'Gorki List', en: 'Gorki List (herbal bitter)', it: 'Gorki List (amaro alle erbe)', ru: 'Gorki List (травяной ликёр)' }, size: '0.03l', price: '2.20' },
      { name: same('Amaro Montenegro'), size: '0.03l', price: '2.20' },
      { name: same('Baileys'), size: '0.03l', price: '2.00' },
      { name: same('Aperol'), size: '0.03l', price: '4.70' },
    ],
  },
  {
    id: 'konjak',
    name: { me: 'Konjak i brendi', en: 'Cognac & brandy', it: 'Cognac e brandy', ru: 'Коньяк и бренди' },
    items: [
      { name: same('Curvosier V.S.'), size: '0.03l', price: '3.50' },
      { name: same('Curvosier V.S.O.P.'), size: '0.03l', price: '5.50' },
      { name: same('Hennessy V.S.'), size: '0.03l', price: '3.50' },
      { name: same('Martell V.S.'), size: '0.03l', price: '3.50' },
      { name: same('Stock'), size: '0.03l', price: '2.20' },
      { name: { me: 'Vinjak V.S.', en: 'Vinjak V.S. (brandy)', it: 'Vinjak V.S. (brandy)', ru: 'Vinjak V.S. (бренди)' }, size: '0.03l', price: '2.20' },
      { name: { me: 'Vinjak 5', en: 'Vinjak 5 (brandy)', it: 'Vinjak 5 (brandy)', ru: 'Vinjak 5 (бренди)' }, size: '0.03l', price: '2.50' },
    ],
  },
  {
    id: 'vodka',
    name: same('Vodka'),
    items: [{ name: same('Vodka Smirnoff'), size: '0.03l', price: '2.00' }],
  },
  {
    id: 'viski',
    name: { me: 'Viski, burbon i džin', en: 'Whiskey, bourbon & gin', it: 'Whisky, bourbon e gin', ru: 'Виски, бурбон и джин' },
    items: [
      { name: same('Famous Grouse'), size: '0.03l', price: '2.50' },
      { name: same("Ballantine's"), size: '0.03l', price: '2.10' },
      { name: same('Jack Daniels'), size: '0.03l', price: '3.50' },
      { name: same('Jack Daniels Honey'), size: '0.03l', price: '3.50' },
      { name: same('Jack Daniels Barrel'), size: '0.03l', price: '4.50' },
      { name: same('Gentlemen Jack'), size: '0.03l', price: '3.70' },
      { name: same('Chivas Regal 12 y.o.'), size: '0.03l', price: '3.50' },
      { name: same('Chivas 18 y.o.'), size: '0.03l', price: '5.50' },
      { name: same('Royal Salute'), size: '0.03l', price: '15.00' },
      { name: same('Johnnie Walker Red'), size: '0.03l', price: '2.30' },
      { name: same('Johnnie Walker Black'), size: '0.03l', price: '3.50' },
      { name: same('Johnnie Walker Gold'), size: '0.03l', price: '5.50' },
      { name: same('Jameson'), size: '0.03l', price: '2.50' },
      { name: same('Jameson Black Barrel'), size: '0.03l', price: '3.00' },
      { name: same('Four Roses'), size: '0.03l', price: '2.50' },
      { name: same('Glenfiddich 12 y.o.'), size: '0.03l', price: '4.50' },
      { name: same('Glenmorangie'), size: '0.03l', price: '3.50' },
      { name: same('Glenlivet'), size: '0.03l', price: '4.00' },
      { name: same('Jim Beam'), size: '0.03l', price: '2.70' },
      { name: same('Jim Beam Black'), size: '0.03l', price: '3.00' },
      { name: same('Gin Gordon'), size: '0.03l', price: '2.50' },
      { name: same('Gin Beefeater'), size: '0.03l', price: '2.50' },
      { name: same('Hendricks'), size: '0.03l', price: '4.00' },
    ],
  },
];
